[package]
name = "fukukouou_server_reborn"
version = "0.1.0"
authors = ["skylinebnr334 <168154498+skylinebnr334@users.noreply.github.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]