-- Your SQL goes here
CREATE TABLE round1_data (
    index	INTEGER NOT NULL UNIQUE,
    team1	INTEGER NOT NULL DEFAULT 0,
    team2	INTEGER NOT NULL DEFAULT 0,
    team3	INTEGER NOT NULL DEFAULT 0,
    team4	INTEGER NOT NULL DEFAULT 0,
    team5	INTEGER NOT NULL DEFAULT 0,
    team6	INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY(index)
)