name: CI
on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-gnu       , use-cross: false , extension: ""   }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract crate information
        shell: bash
        run: |
          echo "PROJECT_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          override: true
          profile: minimal

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: test
          args: --release --target ${{ matrix.job.target }}
      #- name: Build
       # uses: actions-rs/cargo@v1
        #with:
         # use-cross: ${{ matrix.job.use-cross }}
          #command: build
          #args: --release --target ${{ matrix.job.target }}